name: Deploy Azure Function

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "function/**"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy DEV
        if: github.ref == 'refs/heads/dev'
        run: |
          cd function
          func azure functionapp publish function-app-bestringdev --python --verbose

      - name: Deploy PROD
        if: github.ref == 'refs/heads/main'
        run: |
          cd function
          func azure functionapp publish function-app-bestringprod --python